theme: minima
title: LA Rams are all in.
author: D RAE
email: drae@fake.com
description: > # this means to ignore newlines until "baseurl:"
LA Rams are shooting for Super Bowl after signing OBJ

# social links
twitter_username: drae # DO NOT include the @ character, or else the build will fail!
github_username:  gitdrae # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
